### ISSUE TITLE
Vue-Nuxt

### ISSUE THREAD

**Issue by mkalayci35** [marcosvega91/prettier-tailwind#4]
Please add Actually the plugin works for vue  language.

**Comment by marcosvega91** [comment]
Hi @mkalayci35 thanks for opening the issue :)

I'll fix this in the next release. I'll also add support for Typescript. Stay tuned 😣

**Comment by marcosvega91** [comment]
@mkalayci35 I have released a new version of the plugin with the integration with vue. Let me know if it's working as you expected 😄  🥳

**Comment by mkalayci35** [comment]
How to use it is pretitter loaded and when I say fix it does not fix it. :(

**Comment by mkalayci35** [comment]
Thank you. It works.
